// Generated by coverit — https://coverit.dev

import { dirname, relative } from "node:path";
import type {
  CodeScanResult,
  EndpointInfo,
  Framework,
  GeneratedTest,
  GeneratorContext,
  GeneratorResult,
  SkippedItem,
  TestFramework,
} from "../types/index.js";
import { BaseGenerator } from "./base-generator.js";

/**
 * Generates API integration tests for HTTP endpoints.
 * Supports Hono (app.request), Express/NestJS (supertest), and Fastify patterns.
 */
export class ApiTestGenerator extends BaseGenerator {
  async generate(context: GeneratorContext): Promise<GeneratorResult> {
    const { plan, project, scanResults, existingTests } = context;
    const tests: GeneratedTest[] = [];
    const warnings: string[] = [];
    const skipped: SkippedItem[] = [];

    for (const scan of scanResults) {
      if (!plan.target.files.includes(scan.file)) continue;

      const endpoints = scan.endpoints;
      if (endpoints.length === 0) {
        skipped.push({
          target: scan.file,
          reason: "No endpoints detected",
        });
        continue;
      }

      const testFileName = this.generateTestFileName(scan.file, "api");
      const fw = project.testFramework;
      const framework = project.framework;

      const imports = this.buildApiImports(
        scan,
        fw,
        framework,
        testFileName
      );
      const bodyBlocks: string[] = [];
      let testCount = 0;

      for (const endpoint of endpoints) {
        const endpointLabel = `${endpoint.method} ${endpoint.path}`;

        if (this.isAlreadyTested(endpoint.handler, existingTests)) {
          skipped.push({
            target: endpointLabel,
            reason: "Already has tests",
          });
          continue;
        }

        const cases = this.generateEndpointTests(endpoint, framework, fw);
        bodyBlocks.push(this.buildDescribeBlock(endpointLabel, cases));
        testCount += cases.length;
      }

      if (testCount === 0) continue;

      const content = this.assembleTestFile({
        imports,
        body: bodyBlocks,
      });

      tests.push({
        planId: plan.id,
        filePath: testFileName,
        content,
        testType: "api",
        testCount,
        framework: fw === "playwright" || fw === "detox" ? "vitest" : fw,
      });
    }

    return { tests, warnings, skipped };
  }

  // ── Import generation ──────────────────────────────────────

  private buildApiImports(
    scan: CodeScanResult,
    fw: TestFramework,
    framework: Framework,
    testFilePath: string
  ): string[] {
    const lines: string[] = [this.buildImports(fw)];
    const sourcePath = this.relativeImportPath(testFilePath, scan.file);

    switch (framework) {
      case "hono":
        lines.push(`import app from '${sourcePath}';`);
        break;
      case "express":
      case "nestjs":
      case "fastify":
        lines.push("import request from 'supertest';");
        lines.push(`import app from '${sourcePath}';`);
        break;
      default:
        lines.push("import request from 'supertest';");
        lines.push(`import app from '${sourcePath}';`);
    }

    return lines;
  }

  // ── Endpoint test generation ───────────────────────────────

  private generateEndpointTests(
    endpoint: EndpointInfo,
    framework: Framework,
    _fw: TestFramework
  ): string[] {
    const cases: string[] = [];

    // 200/201 success
    cases.push(this.successCase(endpoint, framework));

    // 400 validation error (only for POST/PUT/PATCH with body)
    if (["POST", "PUT", "PATCH"].includes(endpoint.method)) {
      cases.push(this.validationErrorCase(endpoint, framework));
    }

    // 401 unauthorized (if auth middleware detected)
    if (this.hasAuthMiddleware(endpoint)) {
      cases.push(this.unauthorizedCase(endpoint, framework));
    }

    // 404 not found (for endpoints with path params)
    if (endpoint.path.includes(":") || endpoint.path.includes("{")) {
      cases.push(this.notFoundCase(endpoint, framework));
    }

    return cases;
  }

  private successCase(endpoint: EndpointInfo, framework: Framework): string {
    const expectedStatus = endpoint.method === "POST" ? 201 : 200;
    const body = this.buildRequestCall(endpoint, framework, expectedStatus);
    const name = `should return ${expectedStatus} on success`;
    return this.buildAsyncTestCase(name, body);
  }

  private validationErrorCase(
    endpoint: EndpointInfo,
    framework: Framework
  ): string {
    const body = this.buildRequestCall(
      endpoint,
      framework,
      400,
      "{}" // empty body to trigger validation error
    );
    const name = "should return 400 for invalid request body";
    return this.buildAsyncTestCase(name, body);
  }

  private unauthorizedCase(
    endpoint: EndpointInfo,
    framework: Framework
  ): string {
    const body = this.buildRequestCall(
      endpoint,
      framework,
      401,
      undefined,
      false // no auth header
    );
    const name = "should return 401 without authentication";
    return this.buildAsyncTestCase(name, body);
  }

  private notFoundCase(
    endpoint: EndpointInfo,
    framework: Framework
  ): string {
    // Replace path params with non-existent IDs
    const path = endpoint.path
      .replace(/:(\w+)/g, "non-existent-id")
      .replace(/\{(\w+)\}/g, "non-existent-id");

    const modifiedEndpoint = { ...endpoint, path };
    const body = this.buildRequestCall(modifiedEndpoint, framework, 404);
    const name = "should return 404 for non-existent resource";
    return this.buildAsyncTestCase(name, body);
  }

  // ── Request builders per framework ─────────────────────────

  private buildRequestCall(
    endpoint: EndpointInfo,
    framework: Framework,
    expectedStatus: number,
    overrideBody?: string,
    includeAuth = true
  ): string {
    const method = endpoint.method.toLowerCase();
    const path = endpoint.path;
    const hasBody = ["post", "put", "patch"].includes(method);
    const sampleBody = overrideBody ?? this.sampleRequestBody(endpoint);

    if (framework === "hono") {
      return this.honoRequestCall(
        method,
        path,
        expectedStatus,
        hasBody ? sampleBody : undefined,
        includeAuth
      );
    }

    // Express / NestJS / Fastify — supertest
    return this.supertestRequestCall(
      method,
      path,
      expectedStatus,
      hasBody ? sampleBody : undefined,
      includeAuth
    );
  }

  private honoRequestCall(
    method: string,
    path: string,
    expectedStatus: number,
    body?: string,
    includeAuth = true
  ): string {
    const headers: string[] = [];
    if (body) headers.push("'Content-Type': 'application/json'");
    if (includeAuth) headers.push("'Authorization': 'Bearer test-token'");
    const headerStr =
      headers.length > 0 ? `, headers: { ${headers.join(", ")} }` : "";

    const bodyStr = body ? `, body: JSON.stringify(${body})` : "";
    const lines = [
      `const res = await app.request('${path}', { method: '${method.toUpperCase()}'${bodyStr}${headerStr} });`,
      `expect(res.status).toBe(${expectedStatus});`,
    ];

    if (expectedStatus < 300) {
      lines.push(`const data = await res.json();`);
      lines.push(`expect(data).toBeDefined();`);
    }

    return lines.join("\n");
  }

  private supertestRequestCall(
    method: string,
    path: string,
    expectedStatus: number,
    body?: string,
    includeAuth = true
  ): string {
    const lines: string[] = [`const res = await request(app)`];
    lines.push(`  .${method}('${path}')`);

    if (includeAuth) {
      lines.push(`  .set('Authorization', 'Bearer test-token')`);
    }

    if (body) {
      lines.push(`  .send(${body})`);
    }

    lines.push(`  .expect(${expectedStatus});`);

    if (expectedStatus < 300) {
      lines.push(`expect(res.body).toBeDefined();`);
    }

    return lines.join("\n");
  }

  // ── Helpers ────────────────────────────────────────────────

  private hasAuthMiddleware(endpoint: EndpointInfo): boolean {
    return endpoint.middleware.some(
      (m) =>
        m.toLowerCase().includes("auth") ||
        m.toLowerCase().includes("guard") ||
        m.toLowerCase().includes("protect")
    );
  }

  private sampleRequestBody(endpoint: EndpointInfo): string {
    // Produce a minimal plausible JSON body based on endpoint path heuristics
    const path = endpoint.path.toLowerCase();

    if (path.includes("login") || path.includes("auth")) {
      return `{ email: 'test@example.com', password: 'password123' }`;
    }
    if (path.includes("user")) {
      return `{ name: 'Test User', email: 'user@example.com' }`;
    }
    if (path.includes("post") || path.includes("article")) {
      return `{ title: 'Test Title', content: 'Test content body' }`;
    }
    if (path.includes("comment")) {
      return `{ body: 'Test comment' }`;
    }

    return `{ name: 'test', value: 'test-value' }`;
  }

  private relativeImportPath(from: string, to: string): string {
    const rel = relative(dirname(from), to);
    const withoutExt = rel.replace(/\.(ts|tsx|js|jsx)$/, "");
    return rel.startsWith(".") ? withoutExt : `./${withoutExt}`;
  }
}
