// Generated by coverit — https://coverit.dev

import { readdir, readFile } from "node:fs/promises";
import { basename, dirname, extname, join } from "node:path";
import type {
  GeneratorContext,
  GeneratorResult,
  TestFramework,
  TestType,
} from "../types/index.js";

/**
 * Abstract base class for all test generators.
 * Provides shared helpers for building test file content strings,
 * deduplicating against existing tests, and producing consistent output.
 */
export abstract class BaseGenerator {
  abstract generate(context: GeneratorContext): Promise<GeneratorResult>;

  // ── File header ────────────────────────────────────────────

  protected fileHeader(): string {
    return "// Generated by coverit — https://coverit.dev";
  }

  // ── Import builders ────────────────────────────────────────

  protected buildImports(framework: TestFramework): string {
    switch (framework) {
      case "vitest":
        return "import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';";
      case "jest":
        // Jest globals are available without explicit import in most configs,
        // but we import jest for mock utilities.
        return "import { jest } from '@jest/globals';";
      case "playwright":
        return "import { test, expect } from '@playwright/test';";
      case "detox":
        return [
          "import { device, element, by, expect as detoxExpect } from 'detox';",
        ].join("\n");
      default:
        return "// No framework-specific imports";
    }
  }

  // ── Block builders ─────────────────────────────────────────

  protected buildDescribeBlock(name: string, tests: string[]): string {
    const body = tests.map((t) => this.indent(t, 2)).join("\n\n");
    return `describe('${this.escapeString(name)}', () => {\n${body}\n});`;
  }

  protected buildTestCase(name: string, body: string): string {
    const indentedBody = this.indent(body, 2);
    return `it('${this.escapeString(name)}', () => {\n${indentedBody}\n});`;
  }

  protected buildAsyncTestCase(name: string, body: string): string {
    const indentedBody = this.indent(body, 2);
    return `it('${this.escapeString(name)}', async () => {\n${indentedBody}\n});`;
  }

  // ── File naming ────────────────────────────────────────────

  protected generateTestFileName(sourceFile: string, type: TestType): string {
    const dir = dirname(sourceFile);
    const ext = extname(sourceFile);
    const name = basename(sourceFile, ext);

    const suffixMap: Record<TestType, string> = {
      unit: "test",
      integration: "integration.test",
      api: "api.test",
      "e2e-browser": "e2e.test",
      "e2e-mobile": "mobile.test",
      "e2e-desktop": "desktop.test",
      snapshot: "snap.test",
      performance: "perf.test",
    };

    const suffix = suffixMap[type] ?? "test";
    return join(dir, `${name}.${suffix}${ext}`);
  }

  // ── Existing test deduplication ────────────────────────────

  /**
   * Reads all test file contents from a directory so generators
   * can skip creating tests that already exist.
   */
  protected async readExistingTests(dir: string): Promise<string[]> {
    try {
      const entries = await readdir(dir, { recursive: true });
      const testFiles = entries.filter(
        (e) =>
          typeof e === "string" &&
          (e.endsWith(".test.ts") ||
            e.endsWith(".test.tsx") ||
            e.endsWith(".spec.ts") ||
            e.endsWith(".spec.tsx"))
      );

      const contents: string[] = [];
      for (const file of testFiles) {
        try {
          const content = await readFile(join(dir, file), "utf-8");
          contents.push(content);
        } catch {
          // Silently skip unreadable files
        }
      }
      return contents;
    } catch {
      return [];
    }
  }

  /**
   * Returns true if an existing test already covers the given target name
   * (function, class, endpoint, etc.) by scanning existing test contents.
   */
  protected isAlreadyTested(
    targetName: string,
    existingTests: string[]
  ): boolean {
    const pattern = new RegExp(
      `(?:describe|it|test)\\s*\\(\\s*['"\`].*${this.escapeRegExp(targetName)}`,
      "i"
    );
    return existingTests.some((content) => pattern.test(content));
  }

  // ── Utility helpers ────────────────────────────────────────

  protected indent(text: string, spaces: number): string {
    const pad = " ".repeat(spaces);
    return text
      .split("\n")
      .map((line) => (line.trim() ? `${pad}${line}` : line))
      .join("\n");
  }

  protected escapeString(str: string): string {
    return str.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
  }

  private escapeRegExp(str: string): string {
    return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }

  /**
   * Generates a mock variable name from a module path.
   * e.g. "../services/user.service" -> "mockUserService"
   */
  protected mockNameFromModule(modulePath: string): string {
    const name = basename(modulePath, extname(modulePath));
    const camel = name
      .split(/[-.]/)
      .map((part, i) =>
        i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)
      )
      .join("");
    return `mock${camel.charAt(0).toUpperCase()}${camel.slice(1)}`;
  }

  /**
   * Generates a sample value for a given TypeScript type string.
   * Used to create meaningful test data.
   */
  protected sampleValueForType(type: string | null): string {
    if (!type) return "'test-value'";

    const normalized = type.trim().toLowerCase();

    if (normalized === "string") return "'test-string'";
    if (normalized === "number") return "42";
    if (normalized === "boolean") return "true";
    if (normalized === "void" || normalized === "undefined") return "undefined";
    if (normalized === "null") return "null";
    if (normalized.endsWith("[]")) return "[]";
    if (normalized.startsWith("promise<")) {
      const inner = type.slice(8, -1);
      return this.sampleValueForType(inner);
    }
    if (normalized === "date") return "new Date('2025-01-01')";
    if (normalized === "record<string, any>" || normalized === "object")
      return "{}";

    // Default to an empty object for complex types
    return `{} as ${type}`;
  }

  /**
   * Builds a full test file string from its parts.
   */
  protected assembleTestFile(parts: {
    header?: string;
    imports: string[];
    body: string[];
  }): string {
    const sections: string[] = [
      parts.header ?? this.fileHeader(),
      "",
      ...parts.imports,
      "",
      ...parts.body,
      "", // trailing newline
    ];
    return sections.join("\n");
  }
}
