// Generated by coverit — https://coverit.dev

import { readdir, readFile } from "node:fs/promises";
import { basename, dirname, extname, join } from "node:path";
import type {
  CodeScanResult,
  GeneratorContext,
  GeneratorResult,
  TestFramework,
  TestType,
} from "../types/index.js";
import type { AIProvider } from "../ai/types.js";
import type { TestFailure } from "../types/index.js";
import { buildTestGenerationPrompt, buildTestRefinementPrompt } from "../ai/prompts.js";

/**
 * Abstract base class for all test generators.
 * Provides shared helpers for building test file content strings,
 * deduplicating against existing tests, and producing consistent output.
 *
 * When an AIProvider is attached, generators attempt LLM-powered test
 * generation first, falling back to AST-based templates on failure or
 * when no provider is available.
 */
export abstract class BaseGenerator {
  protected aiProvider: AIProvider | null = null;

  abstract generate(context: GeneratorContext): Promise<GeneratorResult>;

  setAIProvider(provider: AIProvider): void {
    this.aiProvider = provider;
  }

  /**
   * Attempts LLM-powered test generation using the attached AI provider.
   * Returns the generated test file content as a string, or null if:
   * - No AI provider is configured
   * - The provider call fails for any reason
   *
   * Callers should fall back to template-based generation when this returns null.
   */
  protected async generateWithAI(params: {
    sourceCode: string;
    scanResult: CodeScanResult;
    testType: TestType;
    framework: TestFramework;
    existingTests?: string[];
  }): Promise<string | null> {
    if (!this.aiProvider) return null;

    try {
      const messages = buildTestGenerationPrompt({
        sourceCode: params.sourceCode,
        scanResult: params.scanResult,
        testType: params.testType,
        framework: params.framework,
        existingTests: params.existingTests,
      });

      const response = await this.aiProvider.generate(messages, {
        temperature: 0.2,
        maxTokens: 16384,
      });

      const content = response.content.trim();
      if (!content) return null;

      const code = this.extractCodeFromResponse(content);

      // Detect truncation via provider signal or syntax check
      if (response.truncated || this.isTruncated(code)) {
        console.warn(`[coverit] AI generation truncated, retrying with higher limit...`);
        const retryResponse = await this.aiProvider!.generate(messages, {
          temperature: 0.2,
          maxTokens: 32768,
        });
        const retryContent = retryResponse.content.trim();
        if (!retryContent) return null;
        const retryCode = this.extractCodeFromResponse(retryContent);
        if (retryResponse.truncated || this.isTruncated(retryCode)) {
          console.error(`[coverit] AI generation still truncated after retry, falling back to template`);
          return null;
        }
        return retryCode;
      }

      return code;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[coverit] AI generation failed: ${msg}`);
      return null;
    }
  }

  /**
   * Attempts to fix failing tests using the AI provider.
   * Sends the failing test code, failure details, and source code to
   * the LLM and returns a corrected test file, or null if unavailable.
   */
  async refineWithAI(params: {
    testCode: string;
    failures: TestFailure[];
    sourceCode: string;
  }): Promise<string | null> {
    if (!this.aiProvider) return null;

    try {
      const messages = buildTestRefinementPrompt({
        testCode: params.testCode,
        failures: params.failures,
        sourceCode: params.sourceCode,
      });

      const response = await this.aiProvider.generate(messages, {
        temperature: 0.2,
        maxTokens: 16384,
      });

      const content = response.content.trim();
      if (!content) return null;

      const code = this.extractCodeFromResponse(content);

      if (response.truncated || this.isTruncated(code)) {
        console.warn(`[coverit] AI refinement truncated, retrying with higher limit...`);
        const retryResponse = await this.aiProvider!.generate(messages, {
          temperature: 0.2,
          maxTokens: 32768,
        });
        const retryContent = retryResponse.content.trim();
        if (!retryContent) return null;
        const retryCode = this.extractCodeFromResponse(retryContent);
        if (retryResponse.truncated || this.isTruncated(retryCode)) {
          console.error(`[coverit] AI refinement still truncated after retry`);
          return null;
        }
        return retryCode;
      }

      return code;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      console.error(`[coverit] AI refinement failed: ${msg}`);
      return null;
    }
  }

  /**
   * Detects if generated code was truncated by counting unbalanced
   * braces and backticks (ignoring those inside string literals).
   */
  private isTruncated(code: string): boolean {
    let braces = 0;
    let backticks = 0;
    let inStr = false;
    let strCh = "";
    for (let i = 0; i < code.length; i++) {
      const ch = code[i]!;
      const prev = code[i - 1] ?? "";
      if (inStr) {
        if (ch === strCh && prev !== "\\") inStr = false;
        continue;
      }
      if (ch === "`") { backticks++; continue; }
      if (ch === '"' || ch === "'") { inStr = true; strCh = ch; continue; }
      if (ch === "{") braces++;
      if (ch === "}") braces--;
    }
    return braces > 0 || backticks % 2 !== 0;
  }

  /**
   * Extracts raw code from an LLM response that may be wrapped in
   * markdown code fences (```typescript ... ``` or ``` ... ```).
   */
  private extractCodeFromResponse(raw: string): string {
    const fenceMatch = raw.match(
      /^```(?:typescript|ts|javascript|js|tsx|jsx)?\s*\n([\s\S]*?)\n```\s*$/
    );
    return fenceMatch?.[1] ? fenceMatch[1].trim() : raw;
  }

  /**
   * Counts the number of test cases in generated code by looking for
   * `it(`, `test(`, and `test.only(` invocations.
   */
  protected countTestCases(code: string): number {
    const itCount = (code.match(/\bit\s*\(/g) || []).length;
    const testCount = (code.match(/\btest\s*\(/g) || []).length;
    return Math.max(itCount + testCount, 1);
  }

  // ── File header ────────────────────────────────────────────

  protected fileHeader(): string {
    return "// Generated by coverit — https://coverit.dev";
  }

  // ── Import builders ────────────────────────────────────────

  protected buildImports(framework: TestFramework): string {
    switch (framework) {
      case "vitest":
        return "import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';";
      case "jest":
        // Jest globals are available without explicit import in most configs,
        // but we import jest for mock utilities.
        return "import { jest } from '@jest/globals';";
      case "playwright":
        return "import { test, expect } from '@playwright/test';";
      case "detox":
        return [
          "import { device, element, by, expect as detoxExpect } from 'detox';",
        ].join("\n");
      default:
        return "// No framework-specific imports";
    }
  }

  // ── Block builders ─────────────────────────────────────────

  protected buildDescribeBlock(name: string, tests: string[]): string {
    const body = tests.map((t) => this.indent(t, 2)).join("\n\n");
    return `describe('${this.escapeString(name)}', () => {\n${body}\n});`;
  }

  protected buildTestCase(name: string, body: string): string {
    const indentedBody = this.indent(body, 2);
    return `it('${this.escapeString(name)}', () => {\n${indentedBody}\n});`;
  }

  protected buildAsyncTestCase(name: string, body: string): string {
    const indentedBody = this.indent(body, 2);
    return `it('${this.escapeString(name)}', async () => {\n${indentedBody}\n});`;
  }

  // ── File naming ────────────────────────────────────────────

  protected generateTestFileName(sourceFile: string, type: TestType): string {
    const dir = dirname(sourceFile);
    const ext = extname(sourceFile);
    const name = basename(sourceFile, ext);

    const suffixMap: Record<TestType, string> = {
      unit: "test",
      integration: "integration.test",
      api: "api.test",
      "e2e-browser": "e2e.test",
      "e2e-mobile": "mobile.test",
      "e2e-desktop": "desktop.test",
      snapshot: "snap.test",
      performance: "perf.test",
    };

    const suffix = suffixMap[type] ?? "test";
    return join(dir, `${name}.${suffix}${ext}`);
  }

  // ── Existing test deduplication ────────────────────────────

  /**
   * Reads all test file contents from a directory so generators
   * can skip creating tests that already exist.
   */
  protected async readExistingTests(dir: string): Promise<string[]> {
    try {
      const entries = await readdir(dir, { recursive: true });
      const testFiles = entries.filter(
        (e) =>
          typeof e === "string" &&
          (e.endsWith(".test.ts") ||
            e.endsWith(".test.tsx") ||
            e.endsWith(".spec.ts") ||
            e.endsWith(".spec.tsx"))
      );

      const contents: string[] = [];
      for (const file of testFiles) {
        try {
          const content = await readFile(join(dir, file), "utf-8");
          contents.push(content);
        } catch {
          // Silently skip unreadable files
        }
      }
      return contents;
    } catch {
      return [];
    }
  }

  /**
   * Returns true if an existing test already covers the given target name
   * (function, class, endpoint, etc.) by scanning existing test contents.
   */
  protected isAlreadyTested(
    targetName: string,
    existingTests: string[]
  ): boolean {
    const pattern = new RegExp(
      `(?:describe|it|test)\\s*\\(\\s*['"\`].*${this.escapeRegExp(targetName)}`,
      "i"
    );
    return existingTests.some((content) => pattern.test(content));
  }

  // ── Utility helpers ────────────────────────────────────────

  protected indent(text: string, spaces: number): string {
    const pad = " ".repeat(spaces);
    return text
      .split("\n")
      .map((line) => (line.trim() ? `${pad}${line}` : line))
      .join("\n");
  }

  protected escapeString(str: string): string {
    return str.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
  }

  private escapeRegExp(str: string): string {
    return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }

  /**
   * Generates a mock variable name from a module path.
   * e.g. "../services/user.service" -> "mockUserService"
   */
  protected mockNameFromModule(modulePath: string): string {
    const name = basename(modulePath, extname(modulePath));
    const camel = name
      .split(/[-.]/)
      .map((part, i) =>
        i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)
      )
      .join("");
    return `mock${camel.charAt(0).toUpperCase()}${camel.slice(1)}`;
  }

  /**
   * Generates a sample value for a given TypeScript type string.
   * Used to create meaningful test data.
   */
  protected sampleValueForType(type: string | null): string {
    if (!type) return "'test-value'";

    const normalized = type.trim().toLowerCase();

    if (normalized === "string") return "'test-string'";
    if (normalized === "number") return "42";
    if (normalized === "boolean") return "true";
    if (normalized === "void" || normalized === "undefined") return "undefined";
    if (normalized === "null") return "null";
    if (normalized.endsWith("[]")) return "[]";
    if (normalized.startsWith("promise<")) {
      const inner = type.slice(8, -1);
      return this.sampleValueForType(inner);
    }
    if (normalized === "date") return "new Date('2025-01-01')";
    if (normalized === "record<string, any>" || normalized === "object")
      return "{}";

    // Default to an empty object for complex types
    return `{} as ${type}`;
  }

  /**
   * Builds a full test file string from its parts.
   */
  protected assembleTestFile(parts: {
    header?: string;
    imports: string[];
    body: string[];
  }): string {
    const sections: string[] = [
      parts.header ?? this.fileHeader(),
      "",
      ...parts.imports,
      "",
      ...parts.body,
      "", // trailing newline
    ];
    return sections.join("\n");
  }
}
