// Generated by coverit — https://coverit.dev

import { dirname, relative } from "node:path";
import type {
  CodeScanResult,
  ComponentInfo,
  FunctionInfo,
  GeneratedTest,
  GeneratorContext,
  GeneratorResult,
  ParamInfo,
  SkippedItem,
  TestFramework,
} from "../types/index.js";
import { BaseGenerator } from "./base-generator.js";

/**
 * Generates tests for Tauri desktop applications:
 * - IPC command invoke tests (mocking @tauri-apps/api/core)
 * - React component tests for Tauri frontends
 */
export class DesktopTestGenerator extends BaseGenerator {
  async generate(context: GeneratorContext): Promise<GeneratorResult> {
    const { plan, project, scanResults, existingTests } = context;
    const tests: GeneratedTest[] = [];
    const warnings: string[] = [];
    const skipped: SkippedItem[] = [];

    for (const scan of scanResults) {
      if (!plan.target.files.includes(scan.file)) continue;

      const hasComponents = scan.components.length > 0;
      const hasTauriCommands = this.detectTauriCommands(scan);

      if (!hasComponents && !hasTauriCommands) {
        skipped.push({
          target: scan.file,
          reason: "No Tauri components or commands detected",
        });
        continue;
      }

      const testFileName = this.generateTestFileName(
        scan.file,
        "e2e-desktop"
      );
      const fw = project.testFramework;

      const imports = this.buildDesktopImports(
        scan,
        fw,
        testFileName,
        hasTauriCommands
      );
      const bodyBlocks: string[] = [];
      let testCount = 0;

      // Tauri IPC command tests
      if (hasTauriCommands) {
        const commandFns = this.getTauriCommandFunctions(scan);
        for (const fn of commandFns) {
          if (this.isAlreadyTested(`invoke:${fn.name}`, existingTests)) {
            skipped.push({
              target: `invoke:${fn.name}`,
              reason: "Already has command tests",
            });
            continue;
          }
          const cases = this.generateCommandTests(fn, fw);
          bodyBlocks.push(
            this.buildDescribeBlock(`Tauri command: ${fn.name}`, cases)
          );
          testCount += cases.length;
        }
      }

      // React component tests
      for (const component of scan.components) {
        if (this.isAlreadyTested(component.name, existingTests)) {
          skipped.push({
            target: component.name,
            reason: "Already has desktop component tests",
          });
          continue;
        }

        const isTauriComponent = this.isTauriIntegrated(component, scan);
        const cases = isTauriComponent
          ? this.generateTauriComponentTests(component, scan, fw)
          : this.generateStandardComponentTests(component, fw);

        bodyBlocks.push(this.buildDescribeBlock(component.name, cases));
        testCount += cases.length;
      }

      if (testCount === 0) continue;

      const content = this.assembleTestFile({
        imports,
        body: bodyBlocks,
      });

      tests.push({
        planId: plan.id,
        filePath: testFileName,
        content,
        testType: "e2e-desktop",
        testCount,
        framework: fw === "playwright" || fw === "detox" ? "vitest" : fw,
      });
    }

    return { tests, warnings, skipped };
  }

  // ── Import generation ──────────────────────────────────────

  private buildDesktopImports(
    scan: CodeScanResult,
    fw: TestFramework,
    testFilePath: string,
    hasTauriCommands: boolean
  ): string[] {
    const lines: string[] = [this.buildImports(fw)];
    const mockFn = fw === "vitest" ? "vi" : "jest";

    // Mock Tauri core if IPC commands are used
    if (hasTauriCommands) {
      lines.push(
        `${mockFn === "vi" ? "vi.mock" : "jest.mock"}('@tauri-apps/api/core', () => ({`,
        `  invoke: ${mockFn}.fn(),`,
        `}));`,
        "",
        `import { invoke } from '@tauri-apps/api/core';`
      );
    }

    // Import testing library for React component tests
    if (scan.components.length > 0) {
      lines.push(
        "import { render, screen, fireEvent, waitFor } from '@testing-library/react';"
      );
    }

    // Import source components/functions
    const sourcePath = this.relativeImportPath(testFilePath, scan.file);
    const exportedNames = scan.exports
      .filter((e) => e.kind === "function" || e.kind === "class")
      .map((e) => e.name);
    const componentNames = scan.components.map((c) => c.name);
    const allNames = [...new Set([...exportedNames, ...componentNames])];

    if (allNames.length > 0) {
      const defaultExport = scan.exports.find((e) => e.isDefault);
      const namedExports = allNames.filter(
        (n) => n !== defaultExport?.name
      );

      if (defaultExport && namedExports.length > 0) {
        lines.push(
          `import ${defaultExport.name}, { ${namedExports.join(", ")} } from '${sourcePath}';`
        );
      } else if (defaultExport) {
        lines.push(`import ${defaultExport.name} from '${sourcePath}';`);
      } else if (namedExports.length > 0) {
        lines.push(
          `import { ${namedExports.join(", ")} } from '${sourcePath}';`
        );
      }
    }

    return lines;
  }

  // ── Tauri command tests ────────────────────────────────────

  private generateCommandTests(
    fn: FunctionInfo,
    fw: TestFramework
  ): string[] {
    const cases: string[] = [];
    const mockFn = fw === "vitest" ? "vi" : "jest";
    const mockedInvoke = `${mockFn === "vi" ? "vi.mocked" : "jest.mocked"}(invoke)`;

    // Build sample payload from function params
    const payload = this.buildCommandPayload(fn.params);
    const payloadStr = payload ? `, ${payload}` : "";
    const returnSample = this.sampleValueForType(fn.returnType);

    // Success case
    cases.push(
      this.buildAsyncTestCase(
        "should invoke command successfully",
        [
          `${mockedInvoke}.mockResolvedValueOnce(${returnSample});`,
          `const result = await invoke('${this.toSnakeCase(fn.name)}'${payloadStr});`,
          `expect(invoke).toHaveBeenCalledWith('${this.toSnakeCase(fn.name)}'${payloadStr});`,
          `expect(result).toEqual(${returnSample});`,
        ].join("\n")
      )
    );

    // Error case
    cases.push(
      this.buildAsyncTestCase(
        "should handle command error",
        [
          `${mockedInvoke}.mockRejectedValueOnce(new Error('Command failed'));`,
          `await expect(invoke('${this.toSnakeCase(fn.name)}'${payloadStr})).rejects.toThrow('Command failed');`,
        ].join("\n")
      )
    );

    // Payload validation (if params exist)
    if (fn.params.length > 0) {
      cases.push(
        this.buildAsyncTestCase(
          "should send correct payload",
          [
            `${mockedInvoke}.mockResolvedValueOnce(undefined);`,
            `await invoke('${this.toSnakeCase(fn.name)}'${payloadStr});`,
            `expect(invoke).toHaveBeenCalledTimes(1);`,
            `const calledPayload = ${mockedInvoke}.mock.calls[0][1];`,
            `expect(calledPayload).toBeDefined();`,
          ].join("\n")
        )
      );
    }

    return cases;
  }

  // ── Tauri-integrated component tests ───────────────────────

  private generateTauriComponentTests(
    component: ComponentInfo,
    _scan: CodeScanResult,
    fw: TestFramework
  ): string[] {
    const cases: string[] = [];
    const mockFn = fw === "vitest" ? "vi" : "jest";
    const mockedInvoke = `${mockFn === "vi" ? "vi.mocked" : "jest.mocked"}(invoke)`;
    const propStr = this.buildDefaultProps(component.props, fw);

    // Rendering test
    cases.push(
      this.buildTestCase(
        "should render without crashing",
        [
          `const { container } = render(<${component.name}${propStr} />);`,
          `expect(container).toBeTruthy();`,
        ].join("\n")
      )
    );

    // Test that Tauri commands are invoked on mount/interaction
    cases.push(
      this.buildAsyncTestCase(
        "should invoke Tauri commands",
        [
          `${mockedInvoke}.mockResolvedValue({});`,
          `render(<${component.name}${propStr} />);`,
          `await waitFor(() => {`,
          `  expect(invoke).toHaveBeenCalled();`,
          `});`,
        ].join("\n")
      )
    );

    // Reset mocks
    cases.push(
      this.buildTestCase(
        "should clean up on unmount",
        [
          `${mockedInvoke}.mockResolvedValue({});`,
          `const { unmount } = render(<${component.name}${propStr} />);`,
          `unmount();`,
          `// Component should unmount without errors`,
        ].join("\n")
      )
    );

    return cases;
  }

  // ── Standard React component tests ─────────────────────────

  private generateStandardComponentTests(
    component: ComponentInfo,
    fw: TestFramework
  ): string[] {
    const cases: string[] = [];
    const propStr = this.buildDefaultProps(component.props, fw);

    // Basic render
    cases.push(
      this.buildTestCase(
        "should render without crashing",
        [
          `const { container } = render(<${component.name}${propStr} />);`,
          `expect(container).toBeTruthy();`,
        ].join("\n")
      )
    );

    // Event handlers
    const eventProps = component.props.filter((p) =>
      /^on[A-Z]/.test(p.name)
    );

    for (const prop of eventProps) {
      const mockName = `mock${prop.name.charAt(0).toUpperCase()}${prop.name.slice(1)}`;
      const mockInit = fw === "vitest" ? "vi.fn()" : "jest.fn()";

      cases.push(
        this.buildTestCase(
          `should handle ${prop.name}`,
          [
            `const ${mockName} = ${mockInit};`,
            `render(<${component.name}${propStr} ${prop.name}={${mockName}} />);`,
            `const target = screen.getByRole('button');`,
            `fireEvent.click(target);`,
            `expect(${mockName}).toHaveBeenCalled();`,
          ].join("\n")
        )
      );
    }

    // Conditional rendering for boolean props
    const boolProps = component.props.filter(
      (p) => p.type?.toLowerCase() === "boolean"
    );

    for (const prop of boolProps) {
      cases.push(
        this.buildTestCase(
          `should render correctly when ${prop.name} is false`,
          [
            `const { container } = render(<${component.name}${propStr} ${prop.name}={false} />);`,
            `expect(container).toBeTruthy();`,
          ].join("\n")
        )
      );
    }

    return cases;
  }

  // ── Detection helpers ──────────────────────────────────────

  private detectTauriCommands(scan: CodeScanResult): boolean {
    return scan.imports.some(
      (m) =>
        m.source === "@tauri-apps/api/core" ||
        m.source === "@tauri-apps/api" ||
        m.source.startsWith("@tauri-apps/")
    );
  }

  private getTauriCommandFunctions(scan: CodeScanResult): FunctionInfo[] {
    // Functions that likely invoke Tauri commands are exported async functions
    // in files that import from @tauri-apps
    return scan.functions.filter((f) => f.isExported && f.isAsync);
  }

  private isTauriIntegrated(
    _component: ComponentInfo,
    scan: CodeScanResult
  ): boolean {
    return this.detectTauriCommands(scan);
  }

  // ── Utility helpers ────────────────────────────────────────

  private buildCommandPayload(params: ParamInfo[]): string | null {
    if (params.length === 0) return null;

    const fields = params
      .map((p) => `${p.name}: ${this.sampleValueForType(p.type)}`)
      .join(", ");

    return `{ ${fields} }`;
  }

  private buildDefaultProps(props: ParamInfo[], fw: TestFramework): string {
    const required = props.filter((p) => !p.isOptional);
    if (required.length === 0) return "";

    const mockInit = fw === "vitest" ? "vi.fn()" : "jest.fn()";
    const assignments = required
      .map((p) => {
        if (/^on[A-Z]/.test(p.name)) return `${p.name}={${mockInit}}`;
        return `${p.name}={${this.sampleValueForType(p.type)}}`;
      })
      .join(" ");

    return ` ${assignments}`;
  }

  private toSnakeCase(name: string): string {
    return name
      .replace(/([a-z])([A-Z])/g, "$1_$2")
      .replace(/([A-Z])([A-Z][a-z])/g, "$1_$2")
      .toLowerCase();
  }

  private relativeImportPath(from: string, to: string): string {
    const rel = relative(dirname(from), to);
    const withoutExt = rel.replace(/\.(ts|tsx|js|jsx)$/, "");
    return rel.startsWith(".") ? withoutExt : `./${withoutExt}`;
  }
}
