// Generated by coverit — https://coverit.dev

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type {
  ComponentInfo,
  GeneratedTest,
  GeneratorContext,
  GeneratorResult,
  SkippedItem,
} from "../types/index.js";
import { BaseGenerator } from "./base-generator.js";

/**
 * Generates Playwright E2E browser tests for page components,
 * forms, navigation, and interactive elements.
 */
export class E2EBrowserGenerator extends BaseGenerator {
  async generate(context: GeneratorContext): Promise<GeneratorResult> {
    const { plan, project, scanResults, existingTests } = context;
    const tests: GeneratedTest[] = [];
    const warnings: string[] = [];
    const skipped: SkippedItem[] = [];

    for (const scan of scanResults) {
      if (!plan.target.files.includes(scan.file)) continue;

      // ── AI-powered generation (preferred path) ──────────────
      if (this.aiProvider) {
        try {
          const sourceCode = await readFile(
            join(project.root, scan.file),
            "utf-8",
          );
          const aiResult = await this.generateWithAI({
            sourceCode,
            scanResult: scan,
            testType: "e2e-browser",
            framework: "playwright",
            existingTests,
          });

          if (aiResult) {
            const testFileName = this.generateTestFileName(
              scan.file,
              "e2e-browser",
            );
            tests.push({
              planId: plan.id,
              filePath: testFileName,
              content: aiResult,
              testType: "e2e-browser",
              testCount: this.countTestCases(aiResult),
              framework: "playwright",
            });
            continue; // Skip template fallback for this file
          }
        } catch {
          // Fall through to template-based generation
        }
      }

      // ── Template-based generation (fallback) ────────────────
      const components = scan.components;
      if (components.length === 0) {
        skipped.push({
          target: scan.file,
          reason: "No components detected for E2E testing",
        });
        continue;
      }

      const testFileName = this.generateTestFileName(scan.file, "e2e-browser");

      const imports = this.buildE2EImports();
      const bodyBlocks: string[] = [];
      let testCount = 0;

      for (const component of components) {
        if (this.isAlreadyTested(component.name, existingTests)) {
          skipped.push({
            target: component.name,
            reason: "Already has E2E tests",
          });
          continue;
        }

        const cases = component.isPage
          ? this.generatePageTests(component)
          : this.generateComponentTests(component);

        bodyBlocks.push(
          this.buildPlaywrightDescribe(component.name, cases)
        );
        testCount += cases.length;
      }

      if (testCount === 0) continue;

      const content = this.assembleTestFile({
        imports,
        body: bodyBlocks,
      });

      tests.push({
        planId: plan.id,
        filePath: testFileName,
        content,
        testType: "e2e-browser",
        testCount,
        framework: "playwright",
      });
    }

    return { tests, warnings, skipped };
  }

  // ── Import generation ──────────────────────────────────────

  private buildE2EImports(): string[] {
    return [this.buildImports("playwright")];
  }

  // ── Playwright-specific describe block ─────────────────────
  // Playwright uses `test.describe` instead of `describe`

  private buildPlaywrightDescribe(
    name: string,
    testCases: string[]
  ): string {
    const body = testCases.map((t) => this.indent(t, 2)).join("\n\n");
    return `test.describe('${this.escapeString(name)}', () => {\n${body}\n});`;
  }

  private buildPlaywrightTest(name: string, body: string): string {
    const indentedBody = this.indent(body, 2);
    return `test('${this.escapeString(name)}', async ({ page }) => {\n${indentedBody}\n});`;
  }

  // ── Page tests ─────────────────────────────────────────────

  private generatePageTests(component: ComponentInfo): string[] {
    const cases: string[] = [];
    const route = this.guessRoute(component.name);

    // Navigation test
    cases.push(
      this.buildPlaywrightTest(
        "should navigate to page",
        [
          `await page.goto('${route}');`,
          `await expect(page).toHaveURL('${route}');`,
        ].join("\n")
      )
    );

    // Content rendering test
    cases.push(
      this.buildPlaywrightTest(
        "should render page content",
        [
          `await page.goto('${route}');`,
          `await expect(page.locator('main, [role="main"], #root')).toBeVisible();`,
        ].join("\n")
      )
    );

    // Heading test
    cases.push(
      this.buildPlaywrightTest(
        "should display page heading",
        [
          `await page.goto('${route}');`,
          `const heading = page.locator('h1, h2').first();`,
          `await expect(heading).toBeVisible();`,
        ].join("\n")
      )
    );

    // Accessibility check
    cases.push(
      this.buildPlaywrightTest(
        "should pass basic accessibility checks",
        [
          `await page.goto('${route}');`,
          `const snapshot = await page.accessibility.snapshot();`,
          `expect(snapshot).toBeTruthy();`,
        ].join("\n")
      )
    );

    // Generate form-specific tests if hooks suggest form usage
    if (this.hasFormHooks(component)) {
      cases.push(...this.generateFormTests(component, route));
    }

    return cases;
  }

  // ── Component tests ────────────────────────────────────────

  private generateComponentTests(component: ComponentInfo): string[] {
    const cases: string[] = [];
    const route = "/"; // default for non-page components

    // Visibility test
    cases.push(
      this.buildPlaywrightTest(
        "should be visible on the page",
        [
          `await page.goto('${route}');`,
          `await expect(page.locator('[data-testid="${this.toKebab(component.name)}"]')).toBeVisible();`,
        ].join("\n")
      )
    );

    // Interaction tests based on detected props
    const clickableProps = component.props.filter((p) =>
      /^on(Click|Press|Submit|Change)/i.test(p.name)
    );

    for (const prop of clickableProps) {
      const action = prop.name.replace(/^on/, "").toLowerCase();
      cases.push(
        this.buildPlaywrightTest(
          `should handle ${action} interaction`,
          [
            `await page.goto('${route}');`,
            `const target = page.locator('[data-testid="${this.toKebab(component.name)}"]');`,
            `await target.click();`,
            `// Verify expected state change after ${action}`,
            `await expect(target).toBeVisible();`,
          ].join("\n")
        )
      );
    }

    // Accessibility check for components
    cases.push(
      this.buildPlaywrightTest(
        "should pass basic accessibility checks",
        [
          `await page.goto('${route}');`,
          `const snapshot = await page.accessibility.snapshot();`,
          `expect(snapshot).toBeTruthy();`,
        ].join("\n")
      )
    );

    return cases;
  }

  // ── Form tests ─────────────────────────────────────────────

  private generateFormTests(
    _component: ComponentInfo,
    route: string
  ): string[] {
    const cases: string[] = [];

    // Fill and submit test
    cases.push(
      this.buildPlaywrightTest(
        "should fill and submit the form",
        [
          `await page.goto('${route}');`,
          `// Fill form fields`,
          `const inputs = page.locator('input:visible, textarea:visible, select:visible');`,
          `const count = await inputs.count();`,
          `for (let i = 0; i < count; i++) {`,
          `  const input = inputs.nth(i);`,
          `  const tagName = await input.evaluate(el => el.tagName.toLowerCase());`,
          `  const type = await input.getAttribute('type') ?? 'text';`,
          `  if (tagName === 'select') {`,
          `    const option = input.locator('option').nth(1);`,
          `    if (await option.count() > 0) await input.selectOption({ index: 1 });`,
          `  } else if (type === 'checkbox' || type === 'radio') {`,
          `    await input.check();`,
          `  } else {`,
          `    await input.fill('test value');`,
          `  }`,
          `}`,
          `// Submit`,
          `const submitBtn = page.locator('button[type="submit"], input[type="submit"]').first();`,
          `if (await submitBtn.count() > 0) await submitBtn.click();`,
        ].join("\n")
      )
    );

    // Validation test
    cases.push(
      this.buildPlaywrightTest(
        "should show validation errors on empty submit",
        [
          `await page.goto('${route}');`,
          `const submitBtn = page.locator('button[type="submit"], input[type="submit"]').first();`,
          `if (await submitBtn.count() > 0) {`,
          `  await submitBtn.click();`,
          `  // Check for validation messages`,
          `  const errorMessages = page.locator('[role="alert"], .error, .invalid-feedback, [aria-invalid="true"]');`,
          `  // Form should either prevent submission or show errors`,
          `  const url = page.url();`,
          `  expect(url).toContain('${route}');`,
          `}`,
        ].join("\n")
      )
    );

    return cases;
  }

  // ── Helpers ────────────────────────────────────────────────

  private guessRoute(componentName: string): string {
    // Convert PascalCase component name to a plausible route
    const kebab = this.toKebab(componentName)
      .replace(/-page$/, "")
      .replace(/-screen$/, "")
      .replace(/-view$/, "");

    if (
      kebab === "home" ||
      kebab === "index" ||
      kebab === "landing" ||
      kebab === "main"
    ) {
      return "/";
    }

    return `/${kebab}`;
  }

  private toKebab(name: string): string {
    return name
      .replace(/([a-z])([A-Z])/g, "$1-$2")
      .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
      .toLowerCase();
  }

  private hasFormHooks(component: ComponentInfo): boolean {
    return component.hooks.some(
      (h) =>
        h.includes("useForm") ||
        h.includes("useField") ||
        h.includes("useState")
    );
  }
}
