// Generated by coverit — https://coverit.dev

import type { ProjectInfo, TestType } from "../types/index.js";
import { ApiTestGenerator } from "./api-test.js";
import { BaseGenerator } from "./base-generator.js";
import { DesktopTestGenerator } from "./desktop-test.js";
import { E2EBrowserGenerator } from "./e2e-browser.js";
import { MobileTestGenerator } from "./mobile-test.js";
import { UnitTestGenerator } from "./unit-test.js";

export { ApiTestGenerator } from "./api-test.js";
export { BaseGenerator } from "./base-generator.js";
export { DesktopTestGenerator } from "./desktop-test.js";
export { E2EBrowserGenerator } from "./e2e-browser.js";
export { MobileTestGenerator } from "./mobile-test.js";
export { UnitTestGenerator } from "./unit-test.js";

/**
 * Factory function that returns the appropriate generator for a given test type.
 * Some test types share generators with different configuration:
 * - integration reuses UnitTestGenerator with integration mode
 * - snapshot reuses E2EBrowserGenerator (captures visual snapshots)
 * - performance reuses ApiTestGenerator (load/timing assertions)
 */
export function createGenerator(
  type: TestType,
  _project: ProjectInfo
): BaseGenerator {
  switch (type) {
    case "unit": {
      return new UnitTestGenerator();
    }

    case "integration": {
      const gen = new UnitTestGenerator();
      gen.setIntegrationMode(true);
      return gen;
    }

    case "api": {
      return new ApiTestGenerator();
    }

    case "e2e-browser": {
      return new E2EBrowserGenerator();
    }

    case "e2e-mobile": {
      return new MobileTestGenerator();
    }

    case "e2e-desktop": {
      return new DesktopTestGenerator();
    }

    case "snapshot": {
      return new E2EBrowserGenerator();
    }

    case "performance": {
      return new ApiTestGenerator();
    }
  }
}
