// Generated by coverit — https://coverit.dev

import type { AIProvider } from "../ai/types.js";
import type { ProjectInfo, TestType } from "../types/index.js";
import { ApiTestGenerator } from "./api-test.js";
import { BaseGenerator } from "./base-generator.js";
import { DesktopTestGenerator } from "./desktop-test.js";
import { E2EBrowserGenerator } from "./e2e-browser.js";
import { MobileTestGenerator } from "./mobile-test.js";
import { UnitTestGenerator } from "./unit-test.js";

export { ApiTestGenerator } from "./api-test.js";
export { BaseGenerator } from "./base-generator.js";
export { DesktopTestGenerator } from "./desktop-test.js";
export { E2EBrowserGenerator } from "./e2e-browser.js";
export { MobileTestGenerator } from "./mobile-test.js";
export { UnitTestGenerator } from "./unit-test.js";

/**
 * Factory function that returns the appropriate generator for a given test type.
 * Some test types share generators with different configuration:
 * - integration reuses UnitTestGenerator with integration mode
 * - snapshot reuses E2EBrowserGenerator (captures visual snapshots)
 * - performance reuses ApiTestGenerator (load/timing assertions)
 *
 * When an AI provider is supplied, the generator will attempt LLM-powered
 * test creation before falling back to template-based output.
 */
export function createGenerator(
  type: TestType,
  _project: ProjectInfo,
  aiProvider?: AIProvider | null,
): BaseGenerator {
  let gen: BaseGenerator;

  switch (type) {
    case "unit": {
      gen = new UnitTestGenerator();
      break;
    }

    case "integration": {
      const unitGen = new UnitTestGenerator();
      unitGen.setIntegrationMode(true);
      gen = unitGen;
      break;
    }

    case "api": {
      gen = new ApiTestGenerator();
      break;
    }

    case "e2e-browser": {
      gen = new E2EBrowserGenerator();
      break;
    }

    case "e2e-mobile": {
      gen = new MobileTestGenerator();
      break;
    }

    case "e2e-desktop": {
      gen = new DesktopTestGenerator();
      break;
    }

    case "snapshot": {
      gen = new E2EBrowserGenerator();
      break;
    }

    case "performance": {
      gen = new ApiTestGenerator();
      break;
    }
  }

  if (aiProvider) {
    gen.setAIProvider(aiProvider);
  }

  return gen;
}
