// Generated by coverit — https://coverit.dev

import { dirname, relative } from "node:path";
import type {
  CodeScanResult,
  ComponentInfo,
  GeneratedTest,
  GeneratorContext,
  GeneratorResult,
  ParamInfo,
  ProjectInfo,
  SkippedItem,
  TestFramework,
} from "../types/index.js";
import { BaseGenerator } from "./base-generator.js";

/**
 * Generates React Native Testing Library tests for mobile screens and components,
 * plus Detox E2E test stubs when the project uses Detox.
 */
export class MobileTestGenerator extends BaseGenerator {
  async generate(context: GeneratorContext): Promise<GeneratorResult> {
    const { plan, project, scanResults, existingTests } = context;
    const tests: GeneratedTest[] = [];
    const warnings: string[] = [];
    const skipped: SkippedItem[] = [];

    for (const scan of scanResults) {
      if (!plan.target.files.includes(scan.file)) continue;

      const components = scan.components;
      if (components.length === 0) {
        skipped.push({
          target: scan.file,
          reason: "No mobile components detected",
        });
        continue;
      }

      const testFileName = this.generateTestFileName(
        scan.file,
        "e2e-mobile"
      );
      const fw = project.testFramework;

      // React Native Testing Library tests
      const imports = this.buildMobileImports(scan, fw, testFileName);
      const bodyBlocks: string[] = [];
      let testCount = 0;

      for (const component of components) {
        if (this.isAlreadyTested(component.name, existingTests)) {
          skipped.push({
            target: component.name,
            reason: "Already has mobile tests",
          });
          continue;
        }

        const cases = component.isPage
          ? this.generateScreenTests(component)
          : this.generateComponentTests(component);

        bodyBlocks.push(this.buildDescribeBlock(component.name, cases));
        testCount += cases.length;
      }

      if (testCount > 0) {
        const content = this.assembleTestFile({
          imports,
          body: bodyBlocks,
        });

        tests.push({
          planId: plan.id,
          filePath: testFileName,
          content,
          testType: "e2e-mobile",
          testCount,
          framework: fw === "detox" ? "detox" : fw,
        });
      }

      // Detox E2E stubs (if project uses Detox)
      if (this.hasDetox(project)) {
        const detoxResult = this.generateDetoxTests(
          scan,
          plan.id,
          existingTests
        );
        if (detoxResult) {
          tests.push(detoxResult);
          testCount += detoxResult.testCount;
        }
      }
    }

    return { tests, warnings, skipped };
  }

  // ── Import generation ──────────────────────────────────────

  private buildMobileImports(
    scan: CodeScanResult,
    fw: TestFramework,
    testFilePath: string
  ): string[] {
    const lines: string[] = [this.buildImports(fw)];

    lines.push(
      "import { render, screen, fireEvent, waitFor } from '@testing-library/react-native';"
    );

    // Import components under test
    const componentNames = scan.components.map((c) => c.name);
    const sourcePath = this.relativeImportPath(testFilePath, scan.file);

    if (componentNames.length > 0) {
      const named = componentNames.join(", ");
      lines.push(`import { ${named} } from '${sourcePath}';`);
    }

    return lines;
  }

  // ── Screen tests (pages/routes) ────────────────────────────

  private generateScreenTests(component: ComponentInfo): string[] {
    const cases: string[] = [];
    const propStr = this.buildDefaultProps(component.props);

    // Renders without crashing
    cases.push(
      this.buildTestCase(
        "should render without crashing",
        [
          `const { toJSON } = render(<${component.name}${propStr} />);`,
          `expect(toJSON()).toBeTruthy();`,
        ].join("\n")
      )
    );

    // Displays expected content
    cases.push(
      this.buildTestCase(
        "should display screen content",
        [
          `render(<${component.name}${propStr} />);`,
          `// Screen should render visible content`,
          `expect(screen.toJSON()).toBeTruthy();`,
        ].join("\n")
      )
    );

    // Navigation props test (React Navigation convention)
    if (this.hasNavigationProp(component)) {
      cases.push(
        this.buildTestCase(
          "should accept navigation props",
          [
            `const mockNavigation = { navigate: jest.fn(), goBack: jest.fn() };`,
            `const mockRoute = { params: {} };`,
            `render(<${component.name} navigation={mockNavigation as any} route={mockRoute as any} />);`,
            `expect(screen.toJSON()).toBeTruthy();`,
          ].join("\n")
        )
      );
    }

    // Data display test
    cases.push(
      this.buildAsyncTestCase(
        "should handle loading and data states",
        [
          `const { toJSON } = render(<${component.name}${propStr} />);`,
          `// Initial render (possibly loading)`,
          `expect(toJSON()).toBeTruthy();`,
          `// Wait for async data if applicable`,
          `await waitFor(() => {`,
          `  expect(screen.toJSON()).toBeTruthy();`,
          `});`,
        ].join("\n")
      )
    );

    return cases;
  }

  // ── Component tests ────────────────────────────────────────

  private generateComponentTests(component: ComponentInfo): string[] {
    const cases: string[] = [];
    const propStr = this.buildDefaultProps(component.props);

    // Basic rendering
    cases.push(
      this.buildTestCase(
        "should render with required props",
        [
          `const { toJSON } = render(<${component.name}${propStr} />);`,
          `expect(toJSON()).toBeTruthy();`,
        ].join("\n")
      )
    );

    // Event handler tests
    const eventProps = component.props.filter((p) =>
      /^on[A-Z]/.test(p.name)
    );

    for (const prop of eventProps) {
      const eventName = prop.name.replace(/^on/, "").toLowerCase();
      const mockName = `mock${prop.name.charAt(0).toUpperCase()}${prop.name.slice(1)}`;

      cases.push(
        this.buildTestCase(
          `should call ${prop.name} handler`,
          [
            `const ${mockName} = jest.fn();`,
            `render(<${component.name}${propStr} ${prop.name}={${mockName}} />);`,
            `// Trigger the ${eventName} event on the primary interactive element`,
            `const target = screen.getByTestId('${this.toKebab(component.name)}');`,
            `fireEvent.press(target);`,
            `expect(${mockName}).toHaveBeenCalled();`,
          ].join("\n")
        )
      );
    }

    // Conditional rendering test for boolean props
    const boolProps = component.props.filter(
      (p) => p.type?.toLowerCase() === "boolean"
    );

    for (const prop of boolProps) {
      cases.push(
        this.buildTestCase(
          `should handle ${prop.name} being false`,
          [
            `const { toJSON } = render(<${component.name}${propStr} ${prop.name}={false} />);`,
            `expect(toJSON()).toBeTruthy();`,
          ].join("\n")
        )
      );
    }

    // Snapshot-like structural test
    cases.push(
      this.buildTestCase(
        "should maintain consistent structure",
        [
          `const { toJSON } = render(<${component.name}${propStr} />);`,
          `expect(toJSON()).toMatchSnapshot();`,
        ].join("\n")
      )
    );

    return cases;
  }

  // ── Detox E2E stubs ────────────────────────────────────────

  private generateDetoxTests(
    scan: CodeScanResult,
    planId: string,
    existingTests: string[]
  ): GeneratedTest | null {
    const screens = scan.components.filter((c) => c.isPage);
    if (screens.length === 0) return null;

    const testFileName = this.generateTestFileName(scan.file, "e2e-mobile")
      .replace(".mobile.test.", ".detox.test.");

    const imports = [
      this.buildImports("detox"),
    ];

    const cases: string[] = [];

    for (const screen of screens) {
      if (this.isAlreadyTested(`detox:${screen.name}`, existingTests)) {
        continue;
      }

      const screenCases = this.generateDetoxScreenTests(screen);
      cases.push(
        this.buildDetoxDescribe(screen.name, screenCases)
      );
    }

    if (cases.length === 0) return null;

    const beforeAll = [
      "beforeAll(async () => {",
      "  await device.launchApp();",
      "});",
      "",
      "beforeEach(async () => {",
      "  await device.reloadReactNative();",
      "});",
    ].join("\n");

    const content = this.assembleTestFile({
      imports,
      body: [beforeAll, ...cases],
    });

    return {
      planId,
      filePath: testFileName,
      content,
      testType: "e2e-mobile",
      testCount: cases.length,
      framework: "detox",
    };
  }

  private generateDetoxScreenTests(screen: ComponentInfo): string[] {
    const testId = this.toKebab(screen.name);
    const cases: string[] = [];

    cases.push(
      this.buildDetoxTest(
        "should be visible",
        [
          `await detoxExpect(element(by.id('${testId}'))).toBeVisible();`,
        ].join("\n")
      )
    );

    cases.push(
      this.buildDetoxTest(
        "should respond to scroll",
        [
          `await element(by.id('${testId}')).scroll(200, 'down');`,
          `await detoxExpect(element(by.id('${testId}'))).toBeVisible();`,
        ].join("\n")
      )
    );

    return cases;
  }

  private buildDetoxDescribe(name: string, tests: string[]): string {
    const body = tests.map((t) => this.indent(t, 2)).join("\n\n");
    return `describe('${this.escapeString(name)}', () => {\n${body}\n});`;
  }

  private buildDetoxTest(name: string, body: string): string {
    const indentedBody = this.indent(body, 2);
    return `it('${this.escapeString(name)}', async () => {\n${indentedBody}\n});`;
  }

  // ── Helpers ────────────────────────────────────────────────

  private hasDetox(project: ProjectInfo): boolean {
    return project.testFramework === "detox";
  }

  private hasNavigationProp(component: ComponentInfo): boolean {
    return component.props.some(
      (p) =>
        p.name === "navigation" ||
        p.name === "route" ||
        p.type?.includes("NavigationProp") ||
        p.type?.includes("RouteProp")
    );
  }

  private buildDefaultProps(props: ParamInfo[]): string {
    const required = props.filter((p) => !p.isOptional);
    if (required.length === 0) return "";

    const propAssignments = required
      .map((p) => {
        if (/^on[A-Z]/.test(p.name)) return `${p.name}={jest.fn()}`;
        return `${p.name}={${this.sampleValueForType(p.type)}}`;
      })
      .join(" ");

    return ` ${propAssignments}`;
  }

  private toKebab(name: string): string {
    return name
      .replace(/([a-z])([A-Z])/g, "$1-$2")
      .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
      .toLowerCase();
  }

  private relativeImportPath(from: string, to: string): string {
    const rel = relative(dirname(from), to);
    const withoutExt = rel.replace(/\.(ts|tsx|js|jsx)$/, "");
    return rel.startsWith(".") ? withoutExt : `./${withoutExt}`;
  }
}
