// Generated by coverit — https://coverit.dev

import { dirname, relative } from "node:path";
import type {
  ClassInfo,
  CodeScanResult,
  FunctionInfo,
  GeneratedTest,
  GeneratorContext,
  GeneratorResult,
  ImportedModule,
  ParamInfo,
  SkippedItem,
  TestFramework,
} from "../types/index.js";
import { BaseGenerator } from "./base-generator.js";

/**
 * Generates unit tests for pure functions, class methods, and utility modules.
 * Supports Vitest and Jest output with idiomatic mocking patterns.
 */
export class UnitTestGenerator extends BaseGenerator {
  private isIntegration = false;

  setIntegrationMode(flag: boolean): void {
    this.isIntegration = flag;
  }

  async generate(context: GeneratorContext): Promise<GeneratorResult> {
    const { plan, project, scanResults, existingTests } = context;
    const tests: GeneratedTest[] = [];
    const warnings: string[] = [];
    const skipped: SkippedItem[] = [];

    const testType = this.isIntegration ? "integration" : "unit";

    for (const scan of scanResults) {
      if (!plan.target.files.includes(scan.file)) continue;

      const functions = scan.functions.filter((f) => f.isExported);
      const classes = scan.classes.filter((c) => c.isExported);

      if (functions.length === 0 && classes.length === 0) {
        skipped.push({
          target: scan.file,
          reason: "No exported functions or classes found",
        });
        continue;
      }

      const testFileName = this.generateTestFileName(scan.file, testType);
      const fw = project.testFramework;

      const imports = this.buildFileImports(scan, fw, testFileName);
      const bodyBlocks: string[] = [];
      let testCount = 0;

      // Generate tests for standalone functions
      for (const fn of functions) {
        if (this.isAlreadyTested(fn.name, existingTests)) {
          skipped.push({
            target: `${scan.file}:${fn.name}`,
            reason: "Already has tests",
          });
          continue;
        }

        const cases = this.generateFunctionTests(fn, fw);
        bodyBlocks.push(this.buildDescribeBlock(fn.name, cases));
        testCount += cases.length;
      }

      // Generate tests for class methods
      for (const cls of classes) {
        if (this.isAlreadyTested(cls.name, existingTests)) {
          skipped.push({
            target: `${scan.file}:${cls.name}`,
            reason: "Already has tests",
          });
          continue;
        }

        const classCases = this.generateClassTests(cls, fw);
        bodyBlocks.push(this.buildDescribeBlock(cls.name, classCases));
        testCount += classCases.length;
      }

      if (testCount === 0) continue;

      const content = this.assembleTestFile({
        imports,
        body: bodyBlocks,
      });

      tests.push({
        planId: plan.id,
        filePath: testFileName,
        content,
        testType,
        testCount,
        framework: fw === "playwright" || fw === "detox" ? "vitest" : fw,
      });
    }

    return { tests, warnings, skipped };
  }

  // ── Import generation ──────────────────────────────────────

  private buildFileImports(
    scan: CodeScanResult,
    fw: TestFramework,
    testFilePath: string
  ): string[] {
    const lines: string[] = [this.buildImports(fw)];

    // Import the source module under test
    const defaultExport = scan.exports.find((e) => e.isDefault);
    const namedExports = scan.exports.filter(
      (e) =>
        !e.isDefault && (e.kind === "function" || e.kind === "class")
    );

    const sourcePath = this.relativeImportPath(testFilePath, scan.file);

    if (defaultExport && namedExports.length > 0) {
      const named = namedExports.map((e) => e.name).join(", ");
      lines.push(
        `import ${defaultExport.name}, { ${named} } from '${sourcePath}';`
      );
    } else if (defaultExport) {
      lines.push(`import ${defaultExport.name} from '${sourcePath}';`);
    } else if (namedExports.length > 0) {
      const named = namedExports.map((e) => e.name).join(", ");
      lines.push(`import { ${named} } from '${sourcePath}';`);
    }

    // Mock external dependencies
    const externalDeps = scan.imports.filter((m) => m.isExternal);
    for (const dep of externalDeps) {
      lines.push(this.buildMock(dep, fw));
    }

    return lines;
  }

  private buildMock(dep: ImportedModule, fw: TestFramework): string {
    const mockFn = fw === "vitest" ? "vi.mock" : "jest.mock";
    if (dep.specifiers.length === 0) {
      return `${mockFn}('${dep.source}');`;
    }
    const specs = dep.specifiers
      .map((s) => `  ${s}: ${fw === "vitest" ? "vi.fn()" : "jest.fn()"},`)
      .join("\n");
    return `${mockFn}('${dep.source}', () => ({\n${specs}\n}));`;
  }

  // ── Function test generation ───────────────────────────────

  private generateFunctionTests(
    fn: FunctionInfo,
    fw: TestFramework
  ): string[] {
    const cases: string[] = [];

    // Happy path
    cases.push(this.happyPathTest(fn, fw));

    // Edge cases for each parameter
    for (const param of fn.params) {
      cases.push(...this.edgeCaseTests(fn, param, fw));
    }

    // Zero-arg functions get a basic invocation test only
    if (fn.params.length === 0 && cases.length === 1) {
      cases.push(this.returnTypeTest(fn));
    }

    // Error-throwing case if complexity is high
    if (fn.complexity > 3) {
      cases.push(this.errorThrowingTest(fn, fw));
    }

    return cases;
  }

  private happyPathTest(fn: FunctionInfo, _fw: TestFramework): string {
    const args = fn.params.map((p) => this.sampleValueForType(p.type)).join(", ");
    const call = fn.isAsync
      ? `await ${fn.name}(${args})`
      : `${fn.name}(${args})`;
    const assertion = fn.returnType
      ? `expect(result).toBeDefined();`
      : `expect(result).toBeUndefined();`;

    const body = `const result = ${call};\n${assertion}`;
    return fn.isAsync
      ? this.buildAsyncTestCase(`should return expected result`, body)
      : this.buildTestCase(`should return expected result`, body);
  }

  private edgeCaseTests(
    fn: FunctionInfo,
    param: ParamInfo,
    _fw: TestFramework
  ): string[] {
    const cases: string[] = [];
    const type = (param.type ?? "").toLowerCase();

    if (type === "string" || !param.type) {
      cases.push(this.edgeCaseTest(fn, param, "''", "empty string"));
    }

    if (type === "number") {
      cases.push(this.edgeCaseTest(fn, param, "0", "zero"));
      cases.push(this.edgeCaseTest(fn, param, "-1", "negative number"));
      cases.push(
        this.edgeCaseTest(fn, param, "Number.MAX_SAFE_INTEGER", "max safe integer")
      );
    }

    if (type === "boolean") {
      cases.push(this.edgeCaseTest(fn, param, "false", "false"));
    }

    if (type.endsWith("[]")) {
      cases.push(this.edgeCaseTest(fn, param, "[]", "empty array"));
    }

    if (param.isOptional) {
      cases.push(this.edgeCaseTest(fn, param, "undefined", "undefined"));
    }

    return cases;
  }

  private edgeCaseTest(
    fn: FunctionInfo,
    targetParam: ParamInfo,
    edgeValue: string,
    label: string
  ): string {
    const args = fn.params
      .map((p) =>
        p.name === targetParam.name
          ? edgeValue
          : this.sampleValueForType(p.type)
      )
      .join(", ");

    const call = fn.isAsync
      ? `await ${fn.name}(${args})`
      : `${fn.name}(${args})`;

    const body = `const result = ${call};\nexpect(result).toBeDefined();`;
    const name = `should handle ${label} for ${targetParam.name}`;

    return fn.isAsync
      ? this.buildAsyncTestCase(name, body)
      : this.buildTestCase(name, body);
  }

  private returnTypeTest(fn: FunctionInfo): string {
    const call = fn.isAsync ? `await ${fn.name}()` : `${fn.name}()`;
    const body = `const result = ${call};\nexpect(result).toBeDefined();`;
    return fn.isAsync
      ? this.buildAsyncTestCase("should return a defined value", body)
      : this.buildTestCase("should return a defined value", body);
  }

  private errorThrowingTest(fn: FunctionInfo, _fw: TestFramework): string {
    // Generate null args to provoke error paths
    const args = fn.params.map(() => "null as any").join(", ");
    const body = fn.isAsync
      ? `await expect(${fn.name}(${args})).rejects.toThrow();`
      : `expect(() => ${fn.name}(${args})).toThrow();`;
    const name = "should throw on invalid input";
    return fn.isAsync
      ? this.buildAsyncTestCase(name, body)
      : this.buildTestCase(name, body);
  }

  // ── Class test generation ──────────────────────────────────

  private generateClassTests(cls: ClassInfo, fw: TestFramework): string[] {
    const cases: string[] = [];

    // Constructor / instantiation test
    cases.push(
      this.buildTestCase("should be instantiable", `const instance = new ${cls.name}();\nexpect(instance).toBeInstanceOf(${cls.name});`)
    );

    // Public methods
    const publicMethods = cls.methods.filter(
      (m) => !m.name.startsWith("_") && !m.name.startsWith("#")
    );

    for (const method of publicMethods) {
      const methodCases = this.generateMethodTests(cls.name, method, fw);
      // Wrap method cases in a nested describe
      cases.push(this.buildDescribeBlock(method.name, methodCases));
    }

    return cases;
  }

  private generateMethodTests(
    className: string,
    method: FunctionInfo,
    _fw: TestFramework
  ): string[] {
    const cases: string[] = [];

    const args = method.params
      .map((p) => this.sampleValueForType(p.type))
      .join(", ");
    const call = method.isAsync
      ? `await instance.${method.name}(${args})`
      : `instance.${method.name}(${args})`;

    const happyBody = `const instance = new ${className}();\nconst result = ${call};\nexpect(result).toBeDefined();`;
    cases.push(
      method.isAsync
        ? this.buildAsyncTestCase("should execute successfully", happyBody)
        : this.buildTestCase("should execute successfully", happyBody)
    );

    // Edge case for methods with params
    if (method.params.length > 0) {
      const nullArgs = method.params.map(() => "null as any").join(", ");
      const errorCall = method.isAsync
        ? `await instance.${method.name}(${nullArgs})`
        : `instance.${method.name}(${nullArgs})`;
      const errorBody = method.isAsync
        ? `const instance = new ${className}();\nawait expect(async () => ${errorCall}).rejects.toThrow();`
        : `const instance = new ${className}();\nexpect(() => ${errorCall}).toThrow();`;
      cases.push(
        method.isAsync
          ? this.buildAsyncTestCase("should handle invalid input", errorBody)
          : this.buildTestCase("should handle invalid input", errorBody)
      );
    }

    return cases;
  }

  // ── Helpers ────────────────────────────────────────────────

  private relativeImportPath(from: string, to: string): string {
    const rel = relative(dirname(from), to);
    const withoutExt = rel.replace(/\.(ts|tsx|js|jsx)$/, "");
    return rel.startsWith(".") ? withoutExt : `./${withoutExt}`;
  }
}
