/**
 * GitHub PR Comment Generator — Produces Markdown for pull request comments.
 *
 * Generates a rich quality report that can be posted as a PR comment by
 * a GitHub Action. The comment includes:
 *
 *   - Overall score with delta from the base branch
 *   - Per-dimension breakdown table
 *   - Top gaps and actionable items
 *   - Footer with tool attribution
 *
 * This module is pure — no GitHub API calls. The caller is responsible
 * for posting the generated Markdown via the GitHub API or `gh` CLI.
 */

import type {
  CoveritManifest,
  Dimension,
} from "../schema/coverit-manifest.js";
import { SCORE_THRESHOLDS } from "../schema/defaults.js";

// ─── Public API ─────────────────────────────────────────────

/**
 * Generate a Markdown PR comment summarizing the quality report.
 *
 * @param manifest - The current project manifest with computed scores
 * @param previousScore - Optional previous overall score (e.g., from the base branch)
 * @returns Markdown string ready for the GitHub PR comment body
 */
export function generatePRComment(
  manifest: CoveritManifest,
  previousScore?: number,
): string {
  const sections: string[] = [];

  sections.push(renderHeader(manifest, previousScore));
  sections.push(renderDimensionTable(manifest));
  sections.push(renderGaps(manifest));
  sections.push(renderFooter());

  return sections.join("\n\n");
}

// ─── Section Renderers ──────────────────────────────────────

function renderHeader(
  manifest: CoveritManifest,
  previousScore?: number,
): string {
  const score = manifest.score.overall;
  const deltaText = previousScore != null
    ? formatDelta(score - previousScore)
    : "";
  const statusEmoji = getOverallStatusEmoji(score, previousScore);

  return [
    "## Coverit Quality Report",
    "",
    `**Score: ${score}/100** ${deltaText}${statusEmoji}`,
  ].join("\n");
}

function renderDimensionTable(manifest: CoveritManifest): string {
  const dimensions: Array<{ key: Dimension; label: string }> = [
    { key: "functionality", label: "Functionality" },
    { key: "security", label: "Security" },
    { key: "stability", label: "Stability" },
    { key: "conformance", label: "Conformance" },
    { key: "regression", label: "Regression" },
  ];

  const rows = dimensions.map(({ key, label }) => {
    const score = manifest.score.breakdown[key];
    const status = getDimensionStatus(score);
    return `| ${label} | ${score} | ${status} |`;
  });

  return [
    "| Dimension | Score | Status |",
    "|-----------|-------|--------|",
    ...rows,
  ].join("\n");
}

function renderGaps(manifest: CoveritManifest): string {
  const gaps = manifest.score.gaps;

  if (gaps.total === 0) {
    return "### Gaps\n\nNo quality gaps detected. Well done!";
  }

  const items: string[] = [];

  // Functionality gaps
  const funcGaps = gaps.byDimension.functionality;
  if (funcGaps.missing > 0) {
    items.push(
      `- ${funcGaps.missing} test${funcGaps.missing !== 1 ? "s" : ""} missing (priority: ${funcGaps.priority})`,
    );
  }

  // Security issues
  const secGaps = gaps.byDimension.security;
  if (secGaps.issues > 0) {
    items.push(
      `- ${secGaps.issues} security issue${secGaps.issues !== 1 ? "s" : ""} need${secGaps.issues === 1 ? "s" : ""} attention (priority: ${secGaps.priority})`,
    );
  }

  // Stability gaps
  const stabGaps = gaps.byDimension.stability;
  if (stabGaps.gaps > 0) {
    items.push(
      `- ${stabGaps.gaps} stability gap${stabGaps.gaps !== 1 ? "s" : ""} detected (priority: ${stabGaps.priority})`,
    );
  }

  // Conformance violations
  const confGaps = gaps.byDimension.conformance;
  if (confGaps.violations > 0) {
    items.push(
      `- ${confGaps.violations} conformance violation${confGaps.violations !== 1 ? "s" : ""} found (priority: ${confGaps.priority})`,
    );
  }

  if (items.length === 0) {
    return "";
  }

  return ["### Gaps", "", ...items].join("\n");
}

function renderFooter(): string {
  return [
    "---",
    "Generated by [coverit](https://coverit.dev)",
  ].join("\n");
}

// ─── Helpers ────────────────────────────────────────────────

/**
 * Format a numeric delta as a signed string with surrounding parens.
 * e.g., 3 -> "(+3 from main) ", -2 -> "(-2 from main) "
 */
function formatDelta(delta: number): string {
  if (delta === 0) return "(no change) ";
  const sign = delta > 0 ? "+" : "";
  return `(${sign}${delta} from main) `;
}

/**
 * Overall status emoji based on score and direction.
 *
 * Uses colored circles to indicate health at a glance:
 *   - Green: healthy (>= 70)
 *   - Yellow: needs attention (>= 50)
 *   - Red: at risk (< 50)
 */
function getOverallStatusEmoji(
  score: number,
  previousScore?: number,
): string {
  if (score >= SCORE_THRESHOLDS.healthy) {
    // If we improved, add a celebration indicator
    if (previousScore != null && score > previousScore) return "🟢";
    return "🟢";
  }
  if (score >= SCORE_THRESHOLDS.needsAttention) return "🟡";
  return "🔴";
}

/**
 * Per-dimension status indicator for the table.
 */
function getDimensionStatus(score: number): string {
  if (score >= SCORE_THRESHOLDS.healthy) return "✅";
  if (score >= SCORE_THRESHOLDS.needsAttention) return "⚠️";
  return "❌";
}
